== Application Server addon
:idprefix: id_ 

image:https://travis-ci.org/forge/as-addon.svg?branch=master["Build Status", link="https://travis-ci.org/forge/as-addon"]

The as addon simplify the interaction with any application serveur.
This addon provides *exports services* for use in other addons. The as addon enables the creation of agnostic application server commands and wizards that run in any API compliant application server addon.

=== Depends on
[options="header"]
|===
|Addon |Exported |Optional

|ui
|no
|no

|projects
|no
|no

|org.jboss.forge.furnace.container:cdi
|no
|no

|as-spi
|yes
|no

|as-api
|no
|no

|as-impl
|no
|no


|===


== Setup
This Addon requires the following installation steps.

=== Add configuration to pom.xml 
To use this addon, you must add it as a dependency in the *pom.xml* of your `forge-addon` classified artifact:
(Make sure the dependency is put all the way to the left, and uses 3 spaces for indentation of GAV)
[source,xml]
----
<dependency>
   <groupId>org.jboss.forge.addon</groupId>
   <artifactId>as</artifactId>
   <classifier>forge-addon</classifier>
   <version>${version}</version>
</dependency>
----


== Features

Service to provide application server provider::
Implement an *Application Server* connector to provide management operations create a `Provider` class.

+
[source,java]
----
public class MyAppServerProvider extends AbstractFacet<Project> implements ApplicationServerProvider
{
...
}
----

 
